const data = {
    products: [{
            _id: "1",
            name: "Nike Slim Shirt",
            category: "shirts",
            image: "/images/p1.jpg",
            price: "2000",
            countInStock: 10,
            brand: "Nike",
            rating: "4.5",
            numReviews: "10",
            description: "High quality Shirt",
        },
        {
            _id: "2",
            name: "Puma office Shirt",
            category: "shirts",
            image: "/images/p2.jpg",
            price: "9000",
            countInStock: 20,
            brand: "Puma",
            rating: "5.0",
            numReviews: "100",
            description: "High quality Shirt",
        },
        {
            _id: "3",
            name: "Van Huesen Slim Shirt",
            category: "shirts",
            image: "/images/p3.jpg",
            price: "8000",
            countInStock: 0,
            brand: "Van Huesen",
            rating: "4.0",
            numReviews: "110",
            description: "High quality Shirt",
        },
        {
            _id: "4",
            name: "Adidas jock Pants",
            category: "trousers",
            image: "/images/p4.jpg",
            price: "7000",
            countInStock: 15,
            brand: "Adidas",
            rating: "3.5",
            numReviews: "9",
            description: "High quality Trousers",
        },
        {
            _id: "5",
            name: "Jumla Slim Pants",
            category: "trousers",
            image: "/images/p5.jpg",
            price: "8000",
            countInStock: 5,
            brand: "Jumla",
            rating: "4.5",
            numReviews: "101",
            description: "High quality Trousers",
        },
        {
            _id: "6",
            name: "Arrow Slim Pants",
            category: "trousers",
            image: "/images/p6.jpg",
            price: "7500",
            countInStock: 12,
            brand: "Arrow",
            rating: "4.0",
            numReviews: "200",
            description: "High quality Trousers",
        },
    ],
};

export default data;